config/routes.rb
RshWeb::Application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :small_steps
      resources :users
      resources :weeks
      resources :excuses
      get 'week/small_steps_for_day', to: 'weeks#small_steps_for_day', as: :small_steps_for_day
      resources :check_ins
      resources :programs
    end
  end

  resources :practices do
    member do
      get :billing
      put :add_billing_info
    end
  end
  devise_for :coaches, controllers: { registrations: "coaches" }
  resources :coaches
  devise_for :users
  resources :users

  resources :programs
  get 'programs/new_big_steps/:id', to: 'programs#new_big_steps', as: :new_big_steps
  patch 'programs/update_big_steps/:id', to: 'programs#update_big_steps', as: :update_big_steps
  get 'programs/new_small_steps/:id', to: 'programs#new_small_steps', as: :new_small_steps
  patch 'programs/update_small_steps/:id', to: 'programs#update_small_steps', as: :update_small_steps

  resources :big_steps
  resources :small_steps do
    resources :note
    resources :attachments
  end
  resources :weeks
  resources :check_ins
  resources :activities
  resources :excuses
  resources :alerts
  resources :reminders
  resources :supporters
  resources :todos
  resources :leads
  resources :referrals
  resources :accomplishments

  root 'home#index'

  get "/coach_terms", to: 'legal_docs#coach_terms'
  get "/user_terms", to: 'legal_docs#user_terms'
  get "/privacy", to: 'legal_docs#privacy'
  get "/support", to: 'home#support'

  get "/rshadmin", to: 'rshadmin#index'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base

  STATUSES = { scheduled: 0, sent: 1 }
  FREQUENCIES = { "Once" => 0, "Daily" => 1, "Weekly" => 2, "Monthly" => 3 }
  DAYS_OF_THE_WEEK = { "Sunday" => 0, "Monday" => 1, "Tuesday" => 2, "Wednesday" => 3, "Thursday" => 4, "Friday" => 5, "Saturday" => 6 }

  belongs_to :program
  has_one :user, through: :program

  before_save :set_send_at

  validates :send_at, presence: true
  validates :send_on, presence: true
  validates :body, presence: true
  validate  :presence_of_recurrence


  def should_send_now?
    require 'active_support/time'

    tz = self.user.timezone
    date_time_now = DateTime.now.in_time_zone(tz)
    send_on_date = self.send_on.in_time_zone(tz)
    # send_at_time = date_time_now.change(hour: send_at.in_time_zone(tz).hour, min: send_at.in_time_zone(tz).min)
    send_at_time = date_time_now.change(hour: send_at.hour, min: send_at.min)
    expire_time = 10.minutes # expire time now acts as a buffer (old code: expire_time = send_at_time + 5.minutes)
    send("check_frequency_#{FREQUENCIES.keys[self.frequency].downcase}", tz, date_time_now, send_on_date, send_at_time, expire_time)
  end

  private

  def presence_of_recurrence
    if daily_recurrence == nil && weekly_recurrence == nil && monthly_recurrence == nil
      errors.add(:base, "Frequency can't be blank")
    end unless frequency == 0
  end

  def set_send_at
    time = Time.zone.parse(send_at.strftime("%H:%M %p"))
    self.send_at = DateTime.parse("#{ send_on } #{ time }")
  end


  def check_frequency_once(tz, date_time_now, send_on_date, send_at_time, expire_time)
    puts "CHECKING FREQ ONCE"
    # send_at_time = send_on_date.change(hour: send_at.in_time_zone(tz).hour, min: send_at.in_time_zone(tz).min)
    send_reminder if (send_on_date.to_date == date_time_now.to_date) && time_between?(date_time_now, send_at_time, expire_time)
  end

  def check_frequency_daily(tz, date_time_now, send_on_date, send_at_time, expire_time)
    puts "CHECKING FREQ DAILY"
    schedule = IceCube::Schedule.new(now = send_on_date) do |s|
      s.add_recurrence_rule(IceCube::Rule.daily(self.daily_recurrence))
    end
    send_reminder if schedule.occurs_on?(date_time_now) && time_between?(date_time_now, send_at_time, expire_time)
  end

  def check_frequency_weekly(tz, date_time_now, send_on_date, send_at_time, expire_time)
    puts "CHECKING FREQ WEEKLY"
    schedule = IceCube::Schedule.new(now = send_on_date) do |s|
      s.add_recurrence_rule(IceCube::Rule.weekly(self.weekly_recurrence).day(send_on_date.wday))
    end
    send_reminder if schedule.occurs_on?(date_time_now) && time_between?(date_time_now, send_at_time, expire_time)
  end

  def check_frequency_monthly(tz, date_time_now, send_on_date, send_at_time, expire_time)
    puts "CHECKING FREQ MONTHLY"
    schedule = IceCube::Schedule.new(now = send_on_date) do |s|
      s.add_recurrence_rule(IceCube::Rule.monthly(self.monthly_recurrence).day_of_month(send_on_date.day))
    end
    send_reminder if schedule.occurs_on?(date_time_now) && time_between?(date_time_now, send_at_time, expire_time)
  end

  def time_between?(date_time_now, send_at_time, expire_time)
    # (date_time_now >= send_at_time && date_time_now <= expire_time) # old code
    date_time_now >= (send_at_time - expire_time) && date_time_now <= (send_at_time + expire_time)
  end

  def send_reminder
      data = { alert: self.body }
      push = Parse::Push.new(data, "user_#{self.user.id}")
      push.type = "ios"
      push.save

      self.last_sent_at = DateTime.now.in_time_zone(self.user.timezone)
      self.save
  end

  def self.scheduled_reminder
    Program.where(status: Program::STATUSES[:active]).each do |program|
      # get scheduled reminders
      @reminders = program.reminders.where(status: STATUSES[:scheduled])

      # loop through each reminder, and determine whether we need to send it now
      @reminders.each do |reminder|
        reminder.should_send_now?
      end
    end
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_filter :authenticate_coach!, :unless => :non_coach_resource_signed_in
  before_filter :authenticate_user!, :unless => :non_user_resource_signed_in
  authorize_resource

  def new
    @program = current_coach.programs.find(params[:program_id])
    @reminder = @program.reminders.new
  end

  def create
    @reminder = Reminder.new(reminder_params)
    if current_coach
      @program = current_coach.programs.find(@reminder.program_id)
    elsif current_user
      @program = current_user.programs.find(@reminder.program_id)
    end

    respond_to do |format|
      if @program.present? && @reminder.save
        format.html { redirect_to(program_path(@program, active: 'notifications'), notice: "Reminder successfully created") }
        format.json { render json: @reminder, status: :created, location: @reminder }
      else
        format.html { redirect_to(program_path(@program, active: 'notifications'), notice: "Your reminder is missing required fields. Please try again.") }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @program = Program.find(@reminder.program_id)
    @reminder.destroy

    respond_to do |format|
      format.html { redirect_to(program_path(@program, active: 'notifications'), notice: "Your reminder has been successfully deleted") }
    end
  end

  def reminder_params
    params.require(:reminder).permit(:body, :frequency, :send_at, :send_on, :program_id, :monthly_recurrence, :weekly_recurrence, :daily_recurrence, :day_of_week, :start_date)
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= simple_form_for reminder, html: { class: "form-vertical" } do |f| %>
  <div class="col-md-12">
    <p>Message should be sent</p>
    <%= f.hidden_field :program_id %>
    <%= f.input :frequency, as: :select, input_html: { class: 'frequency' }, collection: Reminder::FREQUENCIES, label: false, placeholder: 'Frequency' %>
    <div class="clearfix"></div>
  </div>

  <!-- DAILY //-->
  <div class="frequency-option daily col-md-12">
    <%= f.input :daily_recurrence, as: :select, collection: 1..7, label: 'Every' %> <span class="lbl">days</span>
    <div class="clearfix"></div>
  </div>

  <!-- WEEKLY //-->
  <div class="frequency-option weekly col-md-12">
    <%= f.input :weekly_recurrence, as: :select, collection: 1..4, label: 'Every' %> <span class="lbl">weeks on </span><%= f.input :day_of_week, as: :select, collection: Reminder::DAYS_OF_THE_WEEK, label: false %>
    <div class="clearfix"></div>
  </div>

  <!-- MONTHLY //-->
  <div class="frequency-option monthly col-md-12">
    <%= f.input :monthly_recurrence, as: :select, collection: 1..12, label: 'Every' %> <span class="lbl">months</span>
    <div class="clearfix"></div>
  </div>

  <div class="message-send-on col-md-12">
    <div class="col-md-12">
      <%= f.input :send_at, as: :string, input_html: { class: "timepicker" }, label: 'At', placeholder: 'Send Time' %>
    </div>
    <div class="col-md-12">
      <%= f.input :send_on, as: :string, input_html: { class: "datepicker" }, label: 'On', placeholder: 'Date' %>
    </div>
    <%= f.input :body, label: 'Message', placeholder: 'What should it say?', :input_html => { :rows => 4 } %>
    <%= f.submit "Create Reminder", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reminders/_reminder.html.erb
<tr>
  <td><%= reminder.frequency_output %></td>
  <!-- <td><%= reminder.send_at.in_time_zone(reminder.user.timezone).strftime("%B %e, %Y") %></td>
  <td><%= reminder.send_at.in_time_zone(reminder.user.timezone).strftime("%l:%M %p") %></td> -->
  <td><%= reminder.send_at.strftime("%B %e, %Y") %></td>
  <td><%= reminder.send_at.strftime("%l:%M %p") %></td>
  <td><%= reminder.body %></td>
  <td><%= link_to "<span class='glyphicon glyphicon-remove-circle'></span>".html_safe, reminder_path(reminder), data: { confirm: "Are you sure?" }, method: :delete %></td>
</tr>

app/views/reminders/new.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="well">
      <h2>Add a new reminder</h2>
      <%= render 'form', reminder: @reminder %>
    </div>
  </div>
</div>