config/routes.rb
RshWeb::Application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :small_steps
      resources :users
      resources :weeks
      resources :excuses
      get 'week/small_steps_for_day', to: 'weeks#small_steps_for_day', as: :small_steps_for_day
      resources :check_ins
      resources :programs
    end
  end

  resources :practices do
    member do
      get :billing
      put :add_billing_info
    end
  end
  devise_for :coaches, controllers: { registrations: "coaches" }
  resources :coaches
  devise_for :users
  resources :users

  resources :programs
  get 'programs/new_big_steps/:id', to: 'programs#new_big_steps', as: :new_big_steps
  patch 'programs/update_big_steps/:id', to: 'programs#update_big_steps', as: :update_big_steps
  get 'programs/new_small_steps/:id', to: 'programs#new_small_steps', as: :new_small_steps
  patch 'programs/update_small_steps/:id', to: 'programs#update_small_steps', as: :update_small_steps

  resources :big_steps
  resources :small_steps do
    resources :note
    resources :attachments
  end
  resources :weeks
  resources :check_ins
  resources :activities
  resources :excuses
  resources :alerts
  resources :reminders
  resources :supporters
  resources :todos
  resources :leads
  resources :referrals
  resources :accomplishments

  root 'home#index'

  get "/coach_terms", to: 'legal_docs#coach_terms'
  get "/user_terms", to: 'legal_docs#user_terms'
  get "/privacy", to: 'legal_docs#privacy'
  get "/support", to: 'home#support'

  get "/rshadmin", to: 'rshadmin#index'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end
end

app/controllers/api/v1/programs_controller.rb
class Api::V1::ProgramsController < Api::V1::ApplicationController
  
  # Get data for the current program
  def index

    date = Date.parse(params[:date])

    @week = @program.weeks.where("DATE(?) BETWEEN start_date AND end_date", date).first

    unless @week.nil?
      @program_data = @week.as_json(only: :id)

      check_in_status = @week.check_ins.find_by(created_at: date).status rescue nil

      has_check_in = check_in_status != nil
      
      @small_steps = @week.small_steps

      @small_steps_data = @small_steps.as_json(only: [:id, :name, :frequency])

      requires_one_or_more_check_ins = false

      @small_steps_data.each do |small_step|
        begin
          @small_step = @program.small_steps.find(small_step['id'])
          small_step['specific_days'] = @small_step.humanize_days
          
          if @small_step.needs_check_in_on_date(date, true)
            small_step['needs_check_in'] = true
            requires_one_or_more_check_ins = true
          else
            small_step['needs_check_in'] = false
          end
          small_step['can_check_in'] = @small_step.can_check_in_on_date(date)
          small_step['has_check_in'] = @small_step.has_check_in_on_date(date)
        rescue ActiveRecord::RecordNotFound
          small_step['needs_check_in'] = false
          small_step['can_check_in'] = false
          small_step['has_check_in'] = false
        end
      end

      check_in = @week.check_ins.find_by(created_at: date)
      check_in_id = check_in.id unless check_in.nil?
      check_in_comments = check_in.comments unless check_in.nil?

      # @program_data.reverse_merge!({small_steps: @small_steps_data, check_in_status: check_in_status, has_check_in: has_check_in, requires_one_or_more_check_ins: requires_one_or_more_check_ins})
      @program_data.reverse_merge!({small_steps: @small_steps_data, check_in_status: check_in_status, has_check_in: has_check_in, requires_one_or_more_check_ins: requires_one_or_more_check_ins, check_in_comments: check_in_comments})
    else
      @program_data = { program_start_date: @program.start_date } 
    end

    render status: 200, json: {
      success: true,
      data: { program: @program_data }
    }
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :authenticate_coach!, :unless => :non_coach_resource_signed_in
  before_filter :authenticate_admin!, :unless => :non_admin_resource_signed_in
  before_filter :authenticate_user!, :unless => :non_user_resource_signed_in
  authorize_resource

  def index
    if current_coach
      @programs = current_practice.programs
    elsif current_admin
      @programs = Program.all
    end
  end

  def show
    if current_coach
      @program = current_coach.programs.find(params[:id]).decorate
    elsif current_user
      @program = current_user.programs.find(params[:id]).decorate
    elsif current_admin
      @program = Program.find(params[:id]).decorate
    end

    @weeks = @program.weeks.includes(:small_steps => [:big_step]).includes(:check_ins)
    @week = @program.weeks.build(number: 1) # for first week
    @week.small_steps.build # for first week

    @alerts = @program.alerts.decorate
    @reminders = @program.reminders.decorate
    @accomplishments = @program.accomplishments
    # @supporters = @program.supporters
    # @todos = @program.todos

    @active = if params[:active]
      params[:active]
    else
      'steps'
    end
  end

  def new
    @program = Program.new
    @program.build_user
  end

  def create
    @program = Program.new(program_params)
    @program.coaches << current_coach

    if current_coach.practice.hipaa_compliant?
      @program.user.hipaa_compliant = true
      @program.user.create_on_truevault

      first_name = @program.user.first_name
      email = @program.user.email
      @program.user.clear_pii
    end

    respond_to do |format|
      if @program.save

        if @program.user.hipaa_compliant?
          UserMailer.user_invitation_email(@program, current_coach, email, first_name).deliver
        else
          UserMailer.user_invitation_email(@program, current_coach, @program.user.email, @program.user.first_name).deliver
        end

        format.html { redirect_to program_path(@program), notice: "Your client was successfully added and emailed with instructions to download the Steps mobile app" }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end


  # Non restful methods to accommodate the final two steps of creating a new program
  def new_big_steps
    @program = current_practice.programs.find(params[:id])
    @program.big_steps.build
  end

  def new_small_steps
    @program = current_practice.programs.find(params[:id])
    @week = @program.weeks.build(number: 1)
    @week.small_steps.build
    # @program.small_steps.build
  end

  def update_big_steps
    @program = current_practice.programs.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(program_params)
        format.html { redirect_to new_small_steps_path }
      else
        format.html { render action: "new_big_steps" }
      end
    end
  end

  def update_small_steps
    if current_coach
      @program = current_practice.programs.find(params[:id])
    elsif current_user
      @program = current_user.programs.find(params[:id])
    end

    # get the start date of the program (based on the attributes)
    # set the start/end dates of the week
    program_start_date = Date.parse(params[:program][:start_date])
    week_start_date = program_start_date
    week_end_date = program_start_date.end_of_week(:sunday)

    params[:program][:weeks_attributes]["0"][:start_date] = week_start_date
    params[:program][:weeks_attributes]["0"][:end_date] = week_end_date
    @week = @program.weeks.create(number: 1, start_date: week_start_date, end_date: week_end_date)

    # Create new steps
    small_steps = params[:program][:weeks_attributes]["0"][:small_steps_attributes]
    small_steps.each do |small_step|
      big_step = small_step[1][:big_step_id] # If it's a new big step, this will be the new big step name
      big_step_id = big_step.to_i # If it's a big step name, this will be 0 (new big step)
      if big_step_id == 0
        # @week = @program.weeks.build
        @small_step = @week.small_steps.build(small_step[1].except(:_destroy))
        @big_step = @program.big_steps.where(name: big_step).first_or_create!
        small_step[1][:big_step_id] = @big_step.id
        @big_step.small_steps << @small_step
        @big_step.save!
        @week.small_steps << @small_step
      end
    end
    
    respond_to do |format|
      if @program.update_attributes(program_params.except(:weeks_attributes))
        @program.start_date = @program.weeks.first.start_date # Redundant code b/c somehow start_date is still getting lost sometimes
        @program.save # Redundant code b/c somehow start_date is still getting lost sometimes
        format.html { redirect_to program_path(@program) }
      else
        format.html { redirect_to program_path(@program) }
        # format.html { render action: "new_small_steps" }
      end
    end
  end

  def update
    if current_coach
      @program = current_practice.programs.find(params[:id])
    elsif current_user
      @program = current_user.programs.find(params[:id])
    end

    new_coach_name = params[:program][:new_coach]
    if new_coach_name != nil && new_coach_name != ""
      new_coach = current_practice.coaches.where(first_name: new_coach_name.split(" ")[0], last_name: new_coach_name.split(" ")[1]).last
      new_coach.programs << @program

      if @program.user.hipaa_compliant?
        user_pii = @program.user.get_pii
        full_name, first_name = "#{ user_pii['first_name'] } #{ user_pii['last_name'] }", user_pii['first_name']
      else
        full_name, first_name = @program.user.full_name, @program.user.first_name
      end

      UserMailer.coach_shared_client_email(@program, new_coach, current_coach, full_name, first_name).deliver
    end
    
    respond_to do |format|
      if @program.update_attributes(program_params)

        full_name = if @program.user.hipaa_compliant?
          user_pii = @program.user.get_pii
          "#{ user_pii['first_name'] } #{ user_pii['last_name'] }"
        else
          @program.user.full_name
        end

        format.html { redirect_to(program_path(@program, active: 'client-info'), notice: "#{full_name} was successfully updated") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @program = current_practice.programs.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_path, notice: "Successfully deleted." }
    end
  end


  def program_params
    params.require(:program).permit(:purpose, :goal, :start_date, user_attributes: [:hipaa_compliant, :full_name, :email, :first_name, :last_name, :gender, :id], big_steps_attributes: [:name, :id, :_destroy], weeks_attributes: [:number, :start_date, :end_date, small_steps_attributes: [:name, :program_id, :big_step_id, :frequency, :times_per_week, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :_destroy, :id]])
  end
  
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_big_step_fields.html.erb
<div class="nested-fields big-step-fields">
  <%= f.input_field :name %>
  <%= link_to_remove_association "<span class='glyphicon glyphicon-minus-sign'></span>".html_safe, f %>
</div>

app/views/programs/_form.html.erb
<% @user_pii ||= @program.user.get_pii if @program.user.hipaa_compliant? %>

<%= simple_form_for @program, html: { class: "form-vertical" } do |f| %>
  <%= f.fields_for :user do |f| %>

    <% if @user_pii.present? %>
      <%= f.input :first_name, label: false, placeholder: 'First name', input_html: { value: @user_pii['first_name'] } %>
      <%= f.input :last_name, label: false, placeholder: 'Last name', input_html: { value: @user_pii['last_name'] } %>
      <%= f.input :email, label: false, placeholder: 'Email Address', type: 'email', input_html: { value: @user_pii['email'] } %>
    <% else %>
      <%= f.input :first_name, label: false, placeholder: 'First name' %>
      <%= f.input :last_name, label: false, placeholder: 'Last name' %>
      <%= f.input :email, label: false, placeholder: 'Email Address', type: 'email' %>
    <% end %>
    <%= f.input :gender, as: :select, collection: User::GENDERS, label: false, placeholder: 'Gender' %>
  <% end %>
  <%= f.input :purpose, label: "I am here to...", as: :text, placeholder: 'Do what?' %>
  <%= f.input :goal, label: "So I can...", as: :text, placeholder: 'What will sticking to the plan enable you to do?' %>

  <% unless current_user %>
    <%
      coach_signed_in? ? coach = current_coach : coach = @program.coaches.first
      coaches = coach.practice.coaches
      new_coach_options = coaches.map { |c| c.full_name }
      @program.coaches.each { |c| new_coach_options.delete(c.full_name) }
    %>

    <% if @program.coaches.count > 1 %>
      <%= "#{@program.user.first_name}'s coaches:"  %>
      <ul>
        <% @program.coaches.each do |c| %>
          <li><%= c.full_name %></li>
        <% end %>
      </ul>
    <% end %>
    <% if new_coach_options.count > 0 %>
      <%= f.input :new_coach, as: :select, collection: new_coach_options, label: false, placeholder: 'Add a coach' %>
    <% end %>
  <% end %>

  <p class="clear"></p><br/>
  <%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/programs/_program.html.erb
<div class="col-lg-3 col-md-4 col-sm-6">
  <%= link_to program_path(program) do %>
  <div class="well <%= program.activity_status == Program::ACTIVITY_STATUSES[:alert] ? 'alert-client' : 'normal-client' %>">
    <%= image_tag(program.user.avatar.medium.url, height: 123, width: 123, alt: "user avatar") %>
    <h3>
      <% if program.user.hipaa_compliant? %>
        <% user_pii = program.user.get_pii %>
        <%= user_pii['first_name'] %> <%= user_pii['last_name'] %>
      <% else %>
        <%= program.user.full_name %>
      <% end %>
    </h3>
    <div class="check-ins">
      <%= program.daily_checkmarks if program.start_date %>
    </div>
  </div>
  <% end %>
</div>

app/views/programs/_small_step_fields.html.erb
<div class="nested-fields small-step-fields">
  <%= f.hidden_field :program_id, value: @program.id %>
  <%= f.input_field :big_step_id, as: :string, placeholder: 'Big Step', style: "width:200px;" %> :
  <%= f.input_field :name, placeholder: "Small Step" %>
  done
  <%= f.input_field :frequency, class: 'small-step-frequency', as: :select, collection: SmallStep::FREQUENCIES, default: nil %>

  <%= link_to_remove_association "<span class='glyphicon glyphicon-minus-sign'></span>".html_safe, f %>

  <div class="extra-fields">
    <div class="times-per-week">
      <p>How many times per week?</p>
      <%= f.input_field :times_per_week, as: :select, collection: 1..7, default: nil %>
    </div>
    <div class="specific-days-per-week">
      <p>Which days of the week?</p>
      <%= f.input_field :monday, label: false, type: 'checkbox' %>
      <label>Monday</label>
      <%= f.input_field :tuesday, label: false, type: 'checkbox' %>
      <label>Tuesday</label>
      <%= f.input_field :wednesday, label: false, type: 'checkbox' %>
      <label>Wednesday</label>
      <%= f.input_field :thursday, label: false, type: 'checkbox' %>
      <label>Thursday</label>
      <%= f.input_field :friday, label: false, type: 'checkbox' %>
      <label>Friday</label>
      <%= f.input_field :saturday, label: false, type: 'checkbox' %>
      <label>Saturday</label>
        <%= f.input_field :sunday, label: false, type: 'checkbox' %>
      <label>Sunday</label>
    </div>
  </div>
</div>

<script type="text/javascript">
  // when the frequency pull down is changed, show the appropriate "extra" fields
  $(document).on('change','.small-step-frequency',function() {
    displayFrequencyFields( $(this) );
    $('input[type=checkbox]').uniform();
  });
</script>

app/views/programs/_week_fields.html.erb
<div class="nested-fields week-fields">
  <%= f.hidden_field :number %>
  <%= f.hidden_field :start_date %>
  <%= f.hidden_field :end_date %>


  <div id="program_small_steps">
    <%= f.simple_fields_for :small_steps do |small_step| %>
      <%= render 'small_step_fields', f: small_step %>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <%= link_to_add_association "<span id='new-step-btn' class='btn-plus'></span> <span id='plus-button-tooltip' class='plus-button-tooltip' style='display:none;'>Add a new step in Week 1</span>".html_safe, f, :small_steps %>
      </div>
    </div>
  </div>
</div>

<script>
// New step button tooltip
$(document).ready(function() {
  $('#new-step-btn').hover(function() {
    $('#plus-button-tooltip').toggle();
  });
});
</script>

app/views/programs/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 center">
      <h3 class="middle">Add a New User</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 center">
      <ol class="breadcrumb">
        <li></li>
        <li class="active"></li>
        <li></li>
        <li></li>
      </ol>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="well create">
        <p><b><%= @program.user.full_name %> has successfully been added!</b></p>
        <p>Their temporary password is: <span class="code"><%= @program.authentication_token %></span></p>
        <p>They should receive the code shortly via email.</p>
        <div class="row">
          <div class="pull-right">
            <%= link_to 'Build Their Plan', new_big_steps_path(@program), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/index.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <% if current_coach %>
      <div class="col-md-9">
        <h1>Active Clients (<%= @programs.size %>)</h1>
      </div>
      <div class="col-md-3">
         <%= link_to 'Back to Dashboard', coach_path(current_coach), class: 'btn btn-primary add-patient' %>
      </div>
      <% elsif current_admin %>
        <div class="col-md-12">
          <h1>Active Clients (<%= @programs.size %>)</h1>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% if @programs.present? %>
          <table class="table table-striped table-hover">
            <thead>
              <% if current_coach %>
                <tr>
                  <th>Created</th>
                  <th>Client</th>
                  <th>Purpose</th>
                  <th></th>
                </tr>
              <% elsif current_admin %>
                <tr>
                  <th>Practice</th>
                  <th>Coach(es)</th>
                  <th>Client</th>
                  <th class="center">Start Date</th>
                  <th class="center">Wks</th>
                  <th class="center">Stps till</th>
                  <th class="center">CIs</th>
                  <th>Alert</th>
                  <th class="center">? Strk</th>
                  <th></th>
                </tr>
              <% end %>
            </thead>

            <tbody>
              <% if current_coach %>
                <% @programs.each do |program| %>
                  <% user_pii ||= program.user.get_pii if program.user.hipaa_compliant? %>
                  <tr>
                    <td><%= program.created_at.strftime("%m/%d/%y") %></td>
                    <% if user_pii.present? %>
                      <td><%= link_to "#{user_pii['first_name']} #{user_pii['last_name']}", program_path(program) %></td>
                    <% else %>
                      <td><%= link_to program.user.full_name, program_path(program) %></td>
                    <% end %>
                    <td><%= program.purpose %></td>
                    <td>
                      <!-- <%= link_to 'edit', edit_program_path(program) %> | -->
                      <%= link_to 'delete', program, data: { confirm: "Are you sure?" }, method: :delete %>
                    </td>
                  </tr>
                <% end %>
              <% elsif current_admin %>
                <% Practice.all.order(created_at: :desc).each do |practice| %>
                  <% practice.programs.uniq.each do |program| %>
                    <% 
                      coaches = []
                      program.coaches.each { |c| coaches << c.full_name }
                      user_pii ||= program.user.get_pii if program.user.hipaa_compliant?
                    %>
                    <tr>
                      <td><%= link_to truncate(practice.name, length: 11), "#", title: practice.name, class: "plain" %></td>
                      <% if coaches.count > 1 %>
                        <td><%= link_to truncate("(#{coaches.count}) #{coaches.join(', ')}", length: 15), "#", title: coaches.join(", "), class: "plain" %></td>
                      <% else %>
                        <td><%= link_to truncate(coaches.join(", "), length: 11), "#", title: coaches.join(", "), style: "color:#939598;" %></td>
                      <% end %>
                      <% if user_pii.present? %>
                        <td><%= link_to truncate("#{user_pii['first_name']} #{user_pii['last_name']}", length: 11), "#", title: "#{user_pii['first_name']} #{user_pii['last_name']} (#{user_pii['email']})", class: "plain" %></td>
                      <% else %>
                        <td><%= link_to truncate(program.user.full_name, length: 11), "#", title: "#{program.user.full_name} (#{program.user.email})", class: "plain" %></td>
                      <% end %>
                      <td class="center"><%= program.start_date.strftime("%m/%d/%y") if program.start_date %></td>
                      <td class="center"><%= program.weeks.count %></td>
                      <td class="center"><%= program.weeks.last.end_date.strftime("%m/%d/%y") if program.weeks.any? %></td>
                      <td class="center"><%= program.check_ins.count %></td>
                      <td><%= "Alert" if program.activity_status == Program::ACTIVITY_STATUSES[:alert] %></td>
                      <td class="center"><%= program.misses_streak if program.misses_streak %></td>
                      <td><%= link_to 'view', program_path(program) %></td>
                    </tr>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>

          <%#= paginate @users %>
        <% else %>
          <br/>
          <p>No programs have been created yet.</p>
          <br/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<% @user_pii ||= @program.user.get_pii if @program.user.hipaa_compliant?%>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="pull-right">
        <%= image_tag(@program.user.avatar.large.url) %>
      </div>
    </div>
    <div class="col-md-5">
      <h2>
        <% if @user_pii.present? %>
          <%= @user_pii['first_name'] %> <%= @user_pii['last_name'] %>
        <% else %>
          <%= @program.user.full_name %>
        <% end %>
        </h2>
      <p>I am here to <%= @program.purpose.downcase %> so I can <%= @program.goal.downcase %></p>
      <hr/>
    </div>
    <div class="col-md-3">
        <%= link_to 'Back to Dashboard', coach_path(current_coach), class: 'btn btn-primary add-patient' if coach_signed_in? %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" style="margin-top:5px;">
      <ul class="list-inline view">
        <li>View:</li>
        <li class="<%= 'active' if @active == 'steps' %>"><a href="#steps" data-toggle="tab">Steps</a></li>
        <li class="<%= 'active' if @active == 'notifications' %>"><a href="#notifications" data-toggle="tab">Notifications</a></li>
        <li class="<%= 'active' if @active == 'accomplishments' %>"><a href="#accomplishments" data-toggle="tab">Accomplishments</a></li>
        <li class="<%= 'active' if @active == 'client-info' %>"><a href="#client-info" data-toggle="tab">Client Info</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 tab-content">

      <!-- this area needs to be scrollable -->

      <div class="tab-pane scrollable <%= 'active' if @active == 'steps' %>" id="steps">

        <div class="modal" id="small-step-notes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel">Notes</h2>
              </div>
              <div class="modal-body">
              </div>
            </div>
          </div>
        </div>

        <%= render @weeks %>

        <% if @weeks.count == 0 %>
          <%= simple_form_for @program, url: url_for(:action => 'update_small_steps', :controller => 'programs'), html: { class: "form-vertical" } do |f| %>

            <div class="row start-date">
              <div class="col-md-12">
                <p>When do I start?</p>
                <label class="glyphicon glyphicon-calendar"></label>
                <%= f.input :start_date, as: :string, input_html: { class: "datepicker" }, label: false %>
              </div>
            </div>

            <div id="program-weeks">
              <p>What small step(s) should I focus on in my first week?</p>
              <%= f.simple_fields_for :weeks do |week| %>
                <%= render 'week_fields', f: week %>
              <% end %>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div>
                  <%= f.submit "Save", class: 'btn btn-primary' %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="new-week">
            <%= link_to "<span id='new-week-btn' class='btn-plus'></span> <span id='new-week-btn-tooltip' class='plus-button-tooltip' style='display:none;'>Add a new week</span>".html_safe, weeks_path(program_id: @program.id), method: :post %>
          </div>
        <% end %>
      </div>


      <div class="tab-pane <%= 'active' if @active == 'notifications' %>" id="notifications">
        <% unless current_user %>
          <div class="well">
            <h2><%= coach_signed_in? ? "#{current_coach.name}'s Alerts" : "Coach's Alerts" %></h2>
            <p class="adv-settings-desc">Send me email notifications about this client</p>
            <% if @alerts.present? %>
            <%= render @alerts %>
            <% end %>

            <div class="alerts">
              <div class="form">
                <%= render partial: 'alerts/form', locals: { alert: Alert.new(program: @program) } %>
              </div>
            </div>
            <div class="clearfix"></div>

            <%= link_to "<span class='btn-plus'></span>".html_safe, "#", class: 'new-alert-link' %>
          </div>
        <% end %>

        <div class="well">
          <h2>
            <% if @user_pii.present? %>
              <%= "#{ @user_pii['first_name'] }'s Reminders" %>
            <% else %>
              <%= "#{ @program.user.first_name }'s Reminders" %>
            <% end %>
          </h2>
          <p class="adv-settings-desc">Send this client push notifications</p>
          
          <table>
            <thead>
              <tr>
                <th>Frequency</th>
                <th>Date/Starting</th>
                <th>Time</th>
                <th>Message</th>
                <th></th>
              </tr>
            </thead>
              <tr>
                <td>Days with steps</td>
                <td>Start of program</td>
                <td>9:00 PM</td>
                <td>Don't forget to check in today!</td>
                <td></td>
              </tr>
            <%= render @reminders if @reminders.present? %>
          </table>

          <div class="reminder">
            <div class="form" style="margin-bottom:30px;">
              <%= render partial: 'reminders/form', locals: { reminder: Reminder.new(program: @program) } %>
            </div>
          </div>
          <div class="clearfix"></div>
          <%= link_to "<span class='btn-plus'></span>".html_safe, "#", class: 'new-reminder-link' %>
        </div>

        <% if false # Currently not in use, but may be in the future %>
          <div class="well">
            <h2>Accountability Tools</h2>
            <%= render @supporters %>
            <%= link_to "<span class='btn-plus'></span>".html_safe, new_supporter_path(program_id: @program.id) %>
          </div>

          <div class="well">
            <h2>To Dos</h2>
            <%= render @todos %>
            <%= link_to "<span class='btn-plus'></span>".html_safe, new_todo_path(program_id: @program.id) %>
          </div>
        <% end %>
      </div>

      <div class="tab-pane <%= 'active' if @active == 'accomplishments' %>" id="accomplishments">
        <div class="well">
          <h2>Accomplishments</h2>
          <% if @accomplishments.present? %>
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Accomplishment</th>
                  <th>Added By</th>
                  <th></th>
                </tr>
              </thead>
              <%= render @accomplishments %>
            </table>
          <% end %>

          <div class="accomplishments">
            <div class="form">
              <%= render 'accomplishments/form', program: @program %>
            </div>
          </div>
          <div class="clearfix"></div>

          <%= link_to "<span class='btn-plus'></span>".html_safe, "#", class: 'new-accomplishment-link' %>
        </div>
      </div>

      <div class="tab-pane <%= 'active' if @active == 'client-info' %>" id="client-info">
        <div class="well">
          <h2>Client Info</h2>
          <%= render 'form' %>
        </div>
      </div>

      <!-- end scrollable area -->

    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#new-week-btn')
      .hover(function() {
        $('#new-week-btn-tooltip').toggle();
        // alert();
        });
  });
</script>