config/routes.rb
RshWeb::Application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :small_steps
      resources :users
      resources :weeks
      resources :excuses
      get 'week/small_steps_for_day', to: 'weeks#small_steps_for_day', as: :small_steps_for_day
      resources :check_ins
      resources :programs
    end
  end

  resources :practices do
    member do
      get :billing
      put :add_billing_info
    end
  end
  devise_for :coaches, controllers: { registrations: "coaches" }
  resources :coaches
  devise_for :users
  resources :users

  resources :programs
  get 'programs/new_big_steps/:id', to: 'programs#new_big_steps', as: :new_big_steps
  patch 'programs/update_big_steps/:id', to: 'programs#update_big_steps', as: :update_big_steps
  get 'programs/new_small_steps/:id', to: 'programs#new_small_steps', as: :new_small_steps
  patch 'programs/update_small_steps/:id', to: 'programs#update_small_steps', as: :update_small_steps

  resources :big_steps
  resources :small_steps do
    resources :note
    resources :attachments
  end
  resources :weeks
  resources :check_ins
  resources :activities
  resources :excuses
  resources :alerts
  resources :reminders
  resources :supporters
  resources :todos
  resources :leads
  resources :referrals
  resources :accomplishments

  root 'home#index'

  get "/coach_terms", to: 'legal_docs#coach_terms'
  get "/user_terms", to: 'legal_docs#user_terms'
  get "/privacy", to: 'legal_docs#privacy'
  get "/support", to: 'home#support'

  get "/rshadmin", to: 'rshadmin#index'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "landing_layout", only: [:index]
  def index
    if current_coach

      redirect_to coach_path(current_coach)
      # authorize!(:index, :coaches_home)
      # @users = current_coach.users
      # format.html { render "coaches_homepage" }
    elsif current_user
      redirect_to program_path(current_user.programs.last)
    elsif current_admin
      redirect_to rshadmin_path
    else
      @lead = Lead.new
      respond_to do |format|
        format.html { render "guest_homepage" }
      end
    end
  end

  def support
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/guest_homepage.html.erb
<div class="container">

			<div id="header">
					<div class="logo">
						<a href="http://www.mystepsapp.com"><img src="assets/Steps-Logo.png" id="stepslogo"/></a>
					</div>
					<div class="byline">
						<h3>Steps</h3>
						<p>by <a href="http://www.rightsidehealth.com">Right Side Health</a></p>
					</div>
					<div class="topnav">
						<div class="dropdown">
	            <a data-toggle="dropdown" href="#" id="signin">Sign In</a>
	            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	              <li><%= link_to 'As Coach', new_coach_session_path %></li>
	              <li><%= link_to 'As Client', new_user_session_path %></li>
	            </ul>
	          </div>
	          <div><%= link_to image_tag("email.png"), "mailto:contact@rightsidehealth.com", target: "_blank" %></div>
	          <div><%= link_to image_tag("twitter.png"), "https://twitter.com/RightSideHealth", target: "_blank" %></div>
          </div>
			</div>
			
			<div>
				<h1 class="headline">Step Up Your Coaching</h1>
			</div>

			<div style="width:60%; margin:auto;">
				<div id="tagline_box">
					<h4 class="tagline wordwrap"><em>Steps</em> is a web and mobile application for health coaches.  It helps you be with your clients the 99% of the time they aren't in your office -- without a bunch of extra work.</h4>  
					<h4 class="tagline wordwrap">We are currently invite-only.</h4>
				</div>

				<div id="form">
					<%= simple_form_for @lead, html: { class: "TODO", style:"width:80%; margin:auto;" } do |f| %>
					  <%= f.input :name, label: false, placeholder: "Full Name" %>
					  <%= f.input :email, type: 'email', label: false, placeholder: 'Email Address' %>
					  <% if session[:referral_code] %>
				      <%= f.hidden_field :referred_by_code, value: session[:referral_code] %>
				    <% end %>
					  <%= f.submit "Request an Invitation", class: 'btn btn-primary' %>
					<% end %>
					<!--<p id="invite"> (We are currently invite-only) </p>-->
				</div>

				<div id="learnmore">
					<div class="circle"><p class="arrow">&darr;</p>
					</div>
				</div>	
			</div>
</div>
<!--http://www.spydertrap.com/blog/2012/08/user-experience-jquery-smooth-page-anchor-transitions/-->
<a name="more"></a>
<div>
<table id="infographic">
		<tr class="inforow">
			<td class="infoimagebox">
				<div class="imagediv"><img class="infoimage" id="image1" src="assets/schedule2.png" />
				</div>
			</td>
			<td class="infotext">
				<div class="textdiv"><h4>Make a Solid Plan</h4><p>Our plan building tool lets you set long term goals in session with your clients, and break them down into daily actions.  It only takes a couple minutes and won't interfere with your face-to-face interaction.</p>
				</div>
			</td>
		</tr>
		<tr class="inforow">
			<td class="infoimagebox">
				<div class="imagediv"><img class="infoimage" id="image2" src="assets/mobile.png" />
				</div>
			</td>
			<td class="infotext">
				<div class="textdiv"><h4>Follow Progress in Real Time</h4><p>Your clients check in with a simple "yes" or "no" as to whether or not they've done that day's work.  You see their daily check ins, keeping them accountable and you informed.  Plans are fast and easy to adjust on the fly, so your ambitious clients are constantly challenged and struggling clients can get back on track quickly.</p>
				</div>
			</td>
		</tr>
		<tr class="inforow">
			<td class="infoimagebox">
				<div class="imagediv"><img class="infoimage" id="image3" src="assets/desktop.png" />
				</div>
			</td>
			<td class="infotext">
				<div class="textdiv"><h4>Be More Effective and Efficient</h4><p>Steps streamlines the process of outside-the-office interactions, so you can offer a higher level of service while spending less time per client.</p>
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<div id="backtotop">
	<div class="circle2"><p class="arrow2">&uarr;</p>
	</div>
</div>	
			</td>
		</tr>	
</table>
</div>



<script type="text/javascript">
$(".learn_more_btn").click(function() {

    $('html, body').animate({
        scrollTop: $("#infographic").offset().top
    }, 1000);
});

$('.circle')
	.mouseenter(function() {
	// alert(1);
		$(this).fadeTo('fast', .70);
		})
	.mouseleave(function() {
		$(this).fadeTo('fast', 0.4);
		})
	.click(function() {
		$('html, body').animate({scrollTop: $("#infographic").offset().top}, 1000);
	});

$('.circle2')
	.mouseenter(function() {
	// alert(1);
		$(this).fadeTo('fast', .70);
		})
	.mouseleave(function() {
		$(this).fadeTo('fast', 0.4);
		})
	.click(function() {
		$('html, body').animate({scrollTop: $(".container").offset().top}, 1000);
	});
</script>

app/views/home/support.html.erb
<div class="container">
  <div class="well">
    <div class="col-md-12">
      <h2>Steps Customer Support</h2>
			<p>If you have any questions or issues with Steps, please contact us at <a href="mailto:contact@rightsidehealth.com">contact@rightsidehealth.com</a></p>
    </div>
  </div>
</div>