config/routes.rb
RshWeb::Application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :api do
    namespace :v1 do
      resources :sessions
      resources :small_steps
      resources :users
      resources :weeks
      resources :excuses
      get 'week/small_steps_for_day', to: 'weeks#small_steps_for_day', as: :small_steps_for_day
      resources :check_ins
      resources :programs
    end
  end

  resources :practices do
    member do
      get :billing
      put :add_billing_info
    end
  end
  devise_for :coaches, controllers: { registrations: "coaches" }
  resources :coaches
  devise_for :users
  resources :users

  resources :programs
  get 'programs/new_big_steps/:id', to: 'programs#new_big_steps', as: :new_big_steps
  patch 'programs/update_big_steps/:id', to: 'programs#update_big_steps', as: :update_big_steps
  get 'programs/new_small_steps/:id', to: 'programs#new_small_steps', as: :new_small_steps
  patch 'programs/update_small_steps/:id', to: 'programs#update_small_steps', as: :update_small_steps

  resources :big_steps
  resources :small_steps do
    resources :note
    resources :attachments
  end
  resources :weeks
  resources :check_ins
  resources :activities
  resources :excuses
  resources :alerts
  resources :reminders
  resources :supporters
  resources :todos
  resources :leads
  resources :referrals
  resources :accomplishments

  root 'home#index'

  get "/coach_terms", to: 'legal_docs#coach_terms'
  get "/user_terms", to: 'legal_docs#user_terms'
  get "/privacy", to: 'legal_docs#privacy'
  get "/support", to: 'home#support'

  get "/rshadmin", to: 'rshadmin#index'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#error_404'
  end
end

app/models/practice.rb
class Practice < ActiveRecord::Base
	STATUSES = { invited: 0, inactive: 1, active: 2 }

  attr_accessor :stripe_card_token
  
  has_many :coaches, dependent: :destroy
  has_many :programs, through: :coaches, dependent: :destroy
  has_many :users, through: :programs, dependent: :destroy
  has_many :excuses

  accepts_nested_attributes_for :coaches

  validates :terms, acceptance: true

  after_create :create_excuses

  def create_excuses
    ['Almost', 'Tried', 'Confused', 'Weird Day'].each do |excuse_name|
      self.excuses.create(name: excuse_name)
    end
  end
  def save_with_payment
    # Update or Create stripe customer
    if self.stripe_customer_id?
      customer = Stripe::Customer.retrieve(self.stripe_customer_id)
      customer.card = stripe_card_token
      customer.save
      self.update_attributes(
        stripe_card_type: customer.cards.data[0].type,
        stripe_card_last4: customer.cards.data[0].last4)
    else
      customer = Stripe::Customer.create(
        :card => stripe_card_token,
        # :email => email,
        :description => name)
      self.update_attributes(
        stripe_customer_id: customer.id,
        stripe_card_type: customer.cards.data[0].type,
        stripe_card_last4: customer.cards.data[0].last4)
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_filter :authenticate_coach!, only: [:show, :billing]
  before_filter :authenticate_admin!, only: [:index]
  authorize_resource

  def index
    @practices = Practice.all
  end

  def show
    @practice = Practice.find(params[:id])
  end

  def new
    if current_admin || session[:referral_code]
      @practice = Practice.new
      @coach = @practice.coaches.build
    end
  end

  def create
    @practice = Practice.new(practice_params)
    respond_to do |format|
      if @practice.save
        coach = @practice.coaches.first
        coach.role = 'owner'
        if session[:referral_code]
          coach.status = Coach::STATUSES[:active]
          coach.save
          sign_in(coach)
          format.html { redirect_to coach_path(coach), notice: "Welcome!" }
        elsif current_admin
          coach.status = Coach::STATUSES[:invited]
          coach.save
          UserMailer.practice_invitation_email(coach).deliver
          format.html { redirect_to practices_path, notice: "Practice was successfully added" }
        end
        coach.add_example_client
        format.json { render json: @practice, status: :created, location: @practice }
      else
        format.html { render action: "new" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if params[:invite_token]
      @coach = Coach.where(invite_token: params[:invite_token]).first
      @practice = Practice.find(@coach.practice_id)
    elsif current_admin
      @practice = Practice.find(params[:id])
      @coach = @practice.coaches.where(role: "owner").first
    end
  end

  def update
    if params[:invite_token]
      @coach = Coach.where(invite_token: params[:invite_token]).first
      @practice = Practice.find(@coach.practice_id)
    elsif current_admin
      @practice = Practice.find(params[:id])
    end

    respond_to do |format|
      if @practice.update_attributes(practice_params)

        if params[:invite_token]
          @coach.status = Coach::STATUSES[:active]
          @coach.save

          # @coach.confirmation_email
          sign_in :coach, @coach
          format.html { redirect_to coach_path(@coach), notice: "Welcome!" }
        else
          format.html { redirect_to practices_path, notice: "Coach was successfully updated" }
        end
      else
        format.html { render action: "edit" }
      end
    end
  end

  def billing
    @practice = Practice.find(params[:id])
    @coach = @practice.coaches.where(role: "owner").first
  end

  def add_billing_info
    current_practice.stripe_card_token = params[:practice][:stripe_card_token]
    if current_practice.save_with_payment
      redirect_to root_path, notice: "Billing info added successfully"
    else
      render "billing"
    end
  end

  def destroy
    @practice = Practice.find(params[:id])
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_path, notice: "#{@practice.name} was successfully deleted." }
    end
  end

  def practice_params
    params.require(:practice).permit(:hipaa_compliant, :terms, :name, :address, :state, :city, :zip, coaches_attributes: [:id, :referred_by_code, :full_name, :first_name, :last_name, :gender, :email, :password, :password_confirmation])
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_billing_form.html.erb
<%= simple_form_for @practice, url: add_billing_info_practice_path(@practice), html: { method: :put, id: "edit_practice", class: "form-vertical" } do |f| %>
    <legend>Billing Info</legend>

    <div class="form-group string required">
      <%= text_field_tag :card_number, nil, name: nil, type: "text", pattern: "[0-9]*", placeholder: "Credit Card Number", class: "card-number string optional form-control" %>
    </div>
    <div class="form-group string required">
      <%= text_field_tag :card_code, nil, name: nil, type: "text", pattern: "[0-9]*", placeholder: "Security Code (CVV)", class: "card-cvc string optional form-control" %>
    </div>
    <div class="form-group string required">
      <label class="string optional control-label">Expiration (MM/YYYY)</label>
      <br/>
      <%= text_field_tag :card_month, nil, name: nil, type: "text", pattern: "((0[1-9])|(1[0-2]))", placeholder: "MM", class: "card-expiry-month string optional form-control" %>
      <span> / </span>
      <%= text_field_tag :card_year, nil, name: nil, type: "text", pattern: "(19\d\d|20\d\d)", placeholder: "YYYY", class: "card-expiry-year string optional form-control" %>
    </div>
    <br>
    <%= f.hidden_field :stripe_card_token, id: "stripe_card_token" %>
    <div class="payment-errors alert alert-error"></div>
    
    <%= f.submit "Upgrade", class: 'btn btn-primary' %>
<% end %>

app/views/practices/_form.html.erb
<%= simple_form_for @practice, html: { class: "form-vertical" } do |f| %>
  <% if params[:invite_token] || session[:referral_code] %>
    <legend>Your practice</legend>
    <%= f.input :hipaa_compliant %>
    <%= f.input :name, label: false, placeholder: 'Practice Name' %>

    <legend>Your account</legend>
    <%= f.fields_for :coaches do |f| %>
      <%= f.input :full_name, label: false, placeholder: 'Your Name' %>
      <%= f.input :email, type: 'email', label: false, placeholder: 'Email' %>
      <%= f.input :password, type: 'password', label: false, placeholder: 'Password' %>
      <%= f.input :password_confirmation, type: 'password', label: false, placeholder: 'Password confirmation' %>
      <%= f.hidden_field :referred_by_code, value: session[:referral_code] %>
      <%= hidden_field_tag(:invite_token, params[:invite_token]) %>
    <% end %>

    <!--<legend>Billing Info</legend>
    <div class="form-group string required">
      <input class="card-number string optional form-control" maxlength="16" size="255" autocomplete="off" type="text" pattern="[0-9]{13,16}" placeholder="Card Number" />
    </div>
    <div class="form-group string required">
      <input class="card-cvc string optional form-control" maxlength="4" size="255" autocomplete="off" type="text" pattern="[0-9]{3,4}" placeholder="CVC" />
    </div>
    <div class="form-group string required">
      <label class="string optional control-label">Expiration (MM/YYYY)</label>
      <br/>
      <input class="card-expiry-month string optional form-control" maxlength="2" size="2" autocomplete="off" type="text" pattern="((0[1-9])|(1[0-2]))" placeholder="MM" />
      <span> / </span>
      <input class="card-expiry-year string optional form-control" maxlength="4" size="4" autocomplete="off" type="text" pattern="(19\d\d|20\d\d)" placeholder="YYYY" />
    </div>
    <div class="payment-errors alert alert-error"></div>-->

    <div id="coach_terms">
      <%= f.input :terms, as: :boolean, label: "I agree to the #{link_to 'Right Side Health Terms and Conditions', coach_terms_path, target: '_blank' }" %>
    </div>
    <%= f.submit "Sign up", class: 'btn btn-primary' %>
  <% elsif @practice.new_record? %>
    <%= f.input :hipaa_compliant %>
    <%= f.input :name, label: false, placeholder: 'Practice Name' %>
    <%= f.fields_for :coaches do |f| %>
      <%= f.input :full_name, label: false, placeholder: 'Coach Name' %>
      <%= f.input :email, type: 'email', label: false, placeholder: 'Coach Email' %>
    <% end %>
    <%= f.submit "Send Invitation", class: 'btn btn-primary' %>
  <% else %>
    <%= f.input :hipaa_compliant %>
    <%= f.input :name, label: false, placeholder: 'Practice Name' %>
    <%= f.input :address, label: false, placeholder: 'Practice Address' %>
    <%= f.input :city, label: false, placeholder: 'City' %>
    <%= f.input :state, label: false, placeholder: 'State' %>
    <%= f.input :zip, label: false, placeholder: 'Zip' %>
    <%= f.fields_for :coaches do |f| %>
      <%= f.input :full_name, label: false, placeholder: 'Coach Name' %>
      <%= f.input :email, type: 'email', label: false, placeholder: 'Coach Email' %>
      <%= f.input :gender, as: :select, collection: Coach::GENDERS, label: false, placeholder: 'Gender' %>
      <%= f.input :status, as: :select, collection: Coach::STATUSES, label: false, placeholder: 'Status' %>
    <% end %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/practices/billing.html.erb
<div class="container">
  <div class="well">
    <div class="col-md-12">
      <h2>Upgrade to Steps Pro</h2>
      <%= render 'billing_form' %>
    </div>
  </div>
</div>

app/views/practices/edit.html.erb
<!--<% content_for :script do %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">Stripe.setPublishableKey('pk_sgMGdcpy0H8F1OqdH0J7esjxavF0O');</script>
<% end %>-->

<div class="container">
  <div class="well">
    <div class="col-md-12">
      <h2>Sign up</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/practices/index.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-md-12">
        <h1>Listing Practices (<%= @practices.size %>)</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% if @practices.present? %>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>City</th>
                <th>State</th>
                <th>Status</th>
                <th>Stripe ID</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @practices.each do |practice| %>
              <tr>
                <td><%= practice.name %></td>
                <td><%= practice.city %></td>
                <td><%= practice.state %></td>
                <td><%= Coach::STATUSES.keys[practice.coaches.where(role: "owner").first.status] if practice.coaches.any? %></td>
                <td><%= practice.stripe_customer_id %></td>
                <td>
                  <%= link_to 'edit', edit_practice_path(practice) %> |
                  <%= link_to 'delete', practice, data: { confirm: "Are you sure?" }, method: :delete %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

          <%#= paginate @users %>
        <% else %>
          <br/>
          <p>No coaches have been created yet.</p>
          <br/>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="pull-right">
          <%= link_to new_practice_path, class: "btn btn-primary" do %>
            <i class="icon-plus-sign"></i> Invite a New Practice</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/practices/new.html.erb
<% content_for :script do %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">Stripe.setPublishableKey('pk_sgMGdcpy0H8F1OqdH0J7esjxavF0O');</script>
<% end %>

<div class="container">
  <div class="well">
    <div class="col-md-12">
      <h2>Sign up</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/practices/show.html.erb
<div class="container">
  <div class="well">
    <div class="col-md-12">
      <h2>Practice Administration</h2>
      <li><%= link_to 'Manage Coaches', coaches_path %></li>
      <li><%= link_to 'Manage Clients', programs_path %></li>
      <!-- <li><%= link_to 'Manage Excuses', excuses_path %></li> -->
      <!--<li><%= link_to 'Manage Clients', users_path %></li>-->
      <!--<li><%= link_to 'Manage Billing', '#TODO' %></li>-->
    </div>
  </div>
</div>